"""
Service layer for IPL model testing: loads IPL match data, filters by date,
runs resource-model predictions (IPL-fitted params), and prepares data for the web interface.
Uses ipl_innings_snapshots.csv and ipl_male_json/.
"""
import json
import os
from datetime import date, datetime, timedelta
import numpy as np
import pandas as pd

# IPL powerplay-specific parameters (fitted via fit_ipl_powerplay_model.py on ipl_innings_snapshots.csv)
# Phases by overs_completed: 1–6, 7–16, 17–20
# Fitted with fit_ipl_powerplay_model.py (2022 matches excluded)
PHASE_Z0_A = (
    (1.540167, 0.000000),   # overs 1–6
    (1.151021, 0.000000),   # overs 7–9
    (1.275233, 0.019786),   # overs 10–13
    (1.480262, 0.030972),   # overs 14–16
    (1.832008, 0.029681),   # overs 17–20
)
# Resource v2 (DLS-like curve):
# resource = C_k * (1 - exp(-b_k * overs_remaining)) * exp(-a_k * wickets_lost^gamma)
RESOURCE_PHASE_PARAMS = (
    (35.183517, 0.050941, 0.010875),  # overs 1–6: C, b, a_w
    (29.694400, 0.054326, 0.003438),  # overs 7–16
    (45.666991, 0.040952, 0.001940),  # overs 17–20
)
RESOURCE_WICKET_GAMMA = 2.499963
PHASE_BLEND_OVERS = 0.5
# RR_eff = α_k×RR + (1−α_k)×μ_k for powerplay phase k (same bands as Z₀, a: 1–6, 7–16, 17–20)
# Fitted fit_rr_shrinkage.py (2023+ matches, complete innings, MAE vs final_total)
RR_SHRINK_ALPHA_PHASE = (0.130523, 0.289506, 0.350589, 0.381093, 0.617520)
RR_PHASE_MU = (7.993889, 8.614728, 8.512448, 8.546056, 8.700873)
MAX_OVERS = 20
MAX_WICKETS = 10
# Interface / API: only include matches from this date onward (excludes 2022 and earlier)
MIN_MATCH_DATE = date(2023, 1, 1)
MODEL_PARAMS_FILE = "model_params.json"


def _load_runtime_model_params(path: str = MODEL_PARAMS_FILE):
    """
    Load model params generated by update_ipl_daily.py.
    Falls back to in-code defaults when file is missing/invalid.
    """
    if not os.path.isfile(path):
        return
    try:
        with open(path, "r") as f:
            p = json.load(f)

        rr = p.get("rr_shrinkage") or {}
        rm = p.get("resource_model") or {}
        phases = rm.get("phases") or []
        legacy = p.get("phases") or []
        min_date = p.get("min_match_date")

        global RR_SHRINK_ALPHA_PHASE, RR_PHASE_MU
        global RESOURCE_PHASE_PARAMS, RESOURCE_WICKET_GAMMA, PHASE_BLEND_OVERS
        global PHASE_Z0_A, MIN_MATCH_DATE

        if isinstance(rr.get("alpha_by_phase"), list) and len(rr["alpha_by_phase"]) == 5:
            RR_SHRINK_ALPHA_PHASE = tuple(float(x) for x in rr["alpha_by_phase"])
        if isinstance(rr.get("mu_by_phase"), list) and len(rr["mu_by_phase"]) == 5:
            RR_PHASE_MU = tuple(float(x) for x in rr["mu_by_phase"])

        if isinstance(phases, list) and len(phases) == 3:
            RESOURCE_PHASE_PARAMS = tuple(
                (float(ph["C"]), float(ph["b"]), float(ph["a_w"])) for ph in phases
            )
        if rm.get("wicket_gamma") is not None:
            RESOURCE_WICKET_GAMMA = float(rm["wicket_gamma"])
        if rm.get("phase_blend_overs") is not None:
            PHASE_BLEND_OVERS = float(rm["phase_blend_overs"])

        if isinstance(legacy, list) and len(legacy) == 5:
            PHASE_Z0_A = tuple((float(ph["Z0"]), float(ph["a"])) for ph in legacy)

        if isinstance(min_date, str) and len(min_date) >= 10:
            MIN_MATCH_DATE = datetime.strptime(min_date[:10], "%Y-%m-%d").date()
    except Exception:
        # Keep defaults if anything goes wrong loading runtime params.
        pass


_load_runtime_model_params()


def powerplay_phase(overs_completed: float) -> int:
    """Map overs completed in the innings to segment 0, 1, 2, 3, or 4."""
    oc = float(overs_completed)
    if oc <= 6:
        return 0
    if oc <= 9:
        return 1
    if oc <= 13:
        return 2
    if oc <= 16:
        return 3
    return 4


def effective_run_rate(run_rate: float, overs_completed: float) -> float:
    """Shrink observed run rate toward league average μ_k for this powerplay phase k."""
    k = powerplay_phase(overs_completed)
    alpha = RR_SHRINK_ALPHA_PHASE[k]
    mu = RR_PHASE_MU[k]
    r = float(run_rate)
    return alpha * r + (1.0 - alpha) * mu


def _resource_for_phase(
    phase_idx: int,
    overs_remaining: float,
    wickets_remaining: float,
    max_wickets: int = MAX_WICKETS,
    gamma: float = RESOURCE_WICKET_GAMMA,
) -> float:
    # Map 5 phases back to the 3 available V2 resource groups
    mapped_idx = 0 if phase_idx == 0 else (2 if phase_idx == 4 else 1)
    c_k, b_k, a_k = RESOURCE_PHASE_PARAMS[mapped_idx]
    overs_r = max(0.0, float(overs_remaining))
    wickets_lost = max(0.0, float(max_wickets - wickets_remaining))
    return c_k * (1.0 - np.exp(-b_k * overs_r)) * np.exp(-a_k * (wickets_lost ** gamma))


def resource_factor(
    overs_remaining: float,
    wickets_remaining: float,
    overs_completed: float,
    max_wickets: int = MAX_WICKETS,
) -> float:
    """
    Resource curve with phase blending around 6 and 16 overs to avoid sharp kinks.
    """
    oc = float(overs_completed)
    if oc <= 6.0 - PHASE_BLEND_OVERS:
        return _resource_for_phase(0, overs_remaining, wickets_remaining, max_wickets)
    if oc >= 6.0 + PHASE_BLEND_OVERS and oc <= 16.0 - PHASE_BLEND_OVERS:
        return _resource_for_phase(1, overs_remaining, wickets_remaining, max_wickets)
    if oc >= 16.0 + PHASE_BLEND_OVERS:
        return _resource_for_phase(2, overs_remaining, wickets_remaining, max_wickets)

    if 6.0 - PHASE_BLEND_OVERS < oc < 6.0 + PHASE_BLEND_OVERS:
        t = (oc - (6.0 - PHASE_BLEND_OVERS)) / (2.0 * PHASE_BLEND_OVERS)
        r0 = _resource_for_phase(0, overs_remaining, wickets_remaining, max_wickets)
        r1 = _resource_for_phase(1, overs_remaining, wickets_remaining, max_wickets)
        return (1.0 - t) * r0 + t * r1

    t = (oc - (16.0 - PHASE_BLEND_OVERS)) / (2.0 * PHASE_BLEND_OVERS)
    r1 = _resource_for_phase(1, overs_remaining, wickets_remaining, max_wickets)
    r2 = _resource_for_phase(2, overs_remaining, wickets_remaining, max_wickets)
    return (1.0 - t) * r1 + t * r2


def predict_score(
    current_score,
    run_rate,
    overs_remaining,
    wickets_remaining,
    overs_completed,
    Z0=None,
    a=None,
    max_overs=MAX_OVERS,
    max_wickets=MAX_WICKETS,
):
    """
    Predict final score using the IPL resource model.
    Z0 and a are chosen by powerplay phase (overs_completed) unless overridden.
    Uses shrunk effective run rate vs league mean μ_k by powerplay phase.
    """
    if Z0 is None or a is None:
        Z0, a = PHASE_Z0_A[powerplay_phase(overs_completed)]
    rr_eff = effective_run_rate(run_rate, overs_completed)
    rf = resource_factor(overs_remaining, wickets_remaining, overs_completed, max_wickets)
    predicted_runs = rr_eff * rf
    return current_score + predicted_runs

def get_match_metadata(json_dir="ipl_male_json"):
    """Scan JSON match files and return {match_file: {date, teams, event, venue}}."""
    meta = {}
    if not os.path.isdir(json_dir):
        return meta
    for name in os.listdir(json_dir):
        if not name.endswith(".json"):
            continue
        path = os.path.join(json_dir, name)
        try:
            with open(path, "r") as f:
                data = json.load(f)
            info = data.get("info", {})
            dates = info.get("dates", [])
            date_str = dates[0] if dates else None
            teams = info.get("teams", [])
            event = info.get("event", {})
            event_name = event.get("name", "") if isinstance(event, dict) else ""
            venue = info.get("venue", "") or info.get("city", "")
            meta[name] = {
                "date": date_str,
                "teams": teams,
                "event": event_name,
                "venue": venue,
            }
        except (json.JSONDecodeError, KeyError):
            continue
    return meta

def get_recent_and_upcoming(meta, past_days=30):
    """Split matches into recent (past_days) and upcoming (future). past_days=9999 means all time."""
    today = datetime.now().date()
    cutoff = today - timedelta(days=min(past_days, 365 * 50))
    recent, upcoming = [], []
    for match_file, m in meta.items():
        if not m["date"]:
            continue
        try:
            d = datetime.strptime(m["date"], "%Y-%m-%d").date()
            if d >= today:
                upcoming.append((match_file, m, d))
            elif d >= cutoff and d >= MIN_MATCH_DATE:
                recent.append((match_file, m, d))
        except ValueError:
            continue
    recent.sort(key=lambda x: x[2], reverse=True)
    upcoming.sort(key=lambda x: x[2])
    return recent, upcoming

def load_snapshots_csv(csv_path="ipl_innings_snapshots.csv"):
    """Load snapshots CSV; add wickets_remaining. Return None if file missing."""
    if not os.path.isfile(csv_path):
        return None
    df = pd.read_csv(csv_path)
    df["wickets_remaining"] = MAX_WICKETS - df["wickets"]
    return df

def filter_complete_innings_only(df, max_overs=MAX_OVERS, max_wickets=MAX_WICKETS):
    """
    Keep only snapshots from innings that either completed max_overs (20) or were all out (10 wickets).
    Excludes innings that ended early (e.g. rain, DLS) without losing all wickets.
    """
    if df is None or df.empty:
        return df
    g = df.groupby(["match_file", "team"])
    # Final state per innings: max overs_completed and max wickets in that group
    last_overs = g["overs_completed"].transform("max")
    last_wickets = g["wickets"].transform("max")
    complete = (last_overs >= max_overs) | (last_wickets >= max_wickets)
    return df[complete].copy()

def sample_snapshots_at_overs(df_match, overs_points=(10, 15)):
    """For one match's snapshots, pick one row closest to each of overs_points (10 and 15 overs only)."""
    rows = []
    for target_over in overs_points:
        idx = (df_match["overs_completed"] - target_over).abs().idxmin()
        row = df_match.loc[idx]
        if row["overs_remaining"] > 0 and row["run_rate"] > 0 and row["wickets_remaining"] > 0:
            rows.append(row)
    return rows

def build_recent_test_results(recent_matches, df_snapshots):
    """Build list of test results for recent matches: predicted vs actual at 10 and 15 over marks."""
    results = []
    for match_file, m, d in recent_matches:
        df_m = df_snapshots[df_snapshots["match_file"] == match_file]
        if df_m.empty:
            continue
        team_name = df_m["team"].iloc[0]
        snapshots = sample_snapshots_at_overs(df_m)
        for row in snapshots:
            oc = float(row["overs_completed"])
            ph = powerplay_phase(oc)
            pred = predict_score(
                row["current_score"],
                row["run_rate"],
                row["overs_remaining"],
                row["wickets_remaining"],
                oc,
            )
            actual = row["final_total"]
            results.append({
                "match_file": match_file,
                "date": m["date"],
                "teams": m["teams"],
                "event": m["event"],
                "venue": m["venue"],
                "innings_team": str(team_name),
                "at_over": round(oc, 1),
                "powerplay_phase": ph,
                "current_score": int(row["current_score"]),
                "run_rate": round(float(row["run_rate"]), 2),
                "wickets_lost": int(row["wickets"]),
                "overs_remaining": round(float(row["overs_remaining"]), 1),
                "predicted": round(float(pred), 1),
                "actual": int(actual),
                "error": round(float(abs(pred - actual)), 1),
            })
    return results

def get_recent_results(past_days=30, csv_path="ipl_innings_snapshots.csv",
                       json_dir="ipl_male_json"):
    """Public: get recent IPL match test results and summary stats."""
    meta = get_match_metadata(json_dir)
    recent, _ = get_recent_and_upcoming(meta, past_days)
    df = load_snapshots_csv(csv_path)
    def _model_params_payload():
        return {
            "max_overs": MAX_OVERS,
            "max_wickets": MAX_WICKETS,
            "min_match_date": MIN_MATCH_DATE.isoformat(),
            "phases": [
                {
                    "id": "pp1_6",
                    "label": "Overs 1–6",
                    "Z0": PHASE_Z0_A[0][0],
                    "a": PHASE_Z0_A[0][1],
                },
                {
                    "id": "pp7_16",
                    "label": "Overs 7–16",
                    "Z0": PHASE_Z0_A[1][0],
                    "a": PHASE_Z0_A[1][1],
                },
                {
                    "id": "pp17_20",
                    "label": "Overs 17–20",
                    "Z0": PHASE_Z0_A[2][0],
                    "a": PHASE_Z0_A[2][1],
                },
            ],
            "rr_shrinkage": {
                "alpha_by_phase": list(RR_SHRINK_ALPHA_PHASE),
                "mu_by_phase": list(RR_PHASE_MU),
                "phase_labels": ["Overs 1–6", "Overs 7–16", "Overs 17–20"],
                "formula": "RR_eff = α_k×RR + (1−α_k)×μ_k; k = same segment as Z₀,a (2023+ IPL)",
            },
            "resource_model": {
                "phase_labels": ["Overs 1–6", "Overs 7–16", "Overs 17–20"],
                "phases": [
                    {"id": "pp1_6", "label": "Overs 1–6", "C": RESOURCE_PHASE_PARAMS[0][0], "b": RESOURCE_PHASE_PARAMS[0][1], "a_w": RESOURCE_PHASE_PARAMS[0][2]},
                    {"id": "pp7_16", "label": "Overs 7–16", "C": RESOURCE_PHASE_PARAMS[1][0], "b": RESOURCE_PHASE_PARAMS[1][1], "a_w": RESOURCE_PHASE_PARAMS[1][2]},
                    {"id": "pp17_20", "label": "Overs 17–20", "C": RESOURCE_PHASE_PARAMS[2][0], "b": RESOURCE_PHASE_PARAMS[2][1], "a_w": RESOURCE_PHASE_PARAMS[2][2]},
                ],
                "wicket_gamma": RESOURCE_WICKET_GAMMA,
                "phase_blend_overs": PHASE_BLEND_OVERS,
                "formula": "R = C_k*(1-exp(-b_k*overs_remaining))*exp(-a_k*wickets_lost^gamma), blended near 6 and 16 overs",
            },
        }

    if df is None:
        return {"results": [], "summary": {"count": 0, "mae": 0, "message": "IPL CSV not found"}, "model_params": _model_params_payload()}
    df = filter_complete_innings_only(df)
    test_results = build_recent_test_results(recent, df)
    if not test_results:
        return {
            "results": [],
            "summary": {"count": 0, "mae": 0, "message": f"No IPL matches in the last {past_days} days in dataset.", "days_requested": past_days},
            "model_params": _model_params_payload(),
        }
    errors = [r["error"] for r in test_results]
    return {
        "results": test_results,
        "summary": {
            "count": len(test_results),
            "matches_count": len(recent),
            "mae": round(float(np.mean(errors)), 2),
            "rmse": round(float(np.sqrt(np.mean([e**2 for e in errors]))), 2),
            "days_requested": past_days,
        },
        "model_params": _model_params_payload(),
    }

def get_upcoming_fixtures(past_days=30, json_dir="ipl_male_json"):
    """Upcoming fixtures from local IPL JSON (future match dates in the dataset)."""
    meta = get_match_metadata(json_dir)
    _, upcoming = get_recent_and_upcoming(meta, past_days)
    return [
        {
            "match_file": match_file,
            "date": m["date"],
            "teams": m["teams"],
            "event": m["event"],
            "venue": m["venue"],
            "source": "local",
        }
        for match_file, m, _ in upcoming
    ]
